# https://www.imgt.org/IMGTeducation/Aide-memoire/_UK/aminoacids/IMGTclasses.html
AA_GROUPS = {
    'hydropathy_classes': {
        "A": "hydrophobic",
        "R": "hydrophilic",
        "N": "hydrophilic",
        "D": "hydrophilic",
        "C": "hydrophobic",
        "Q": "hydrophilic",
        "E": "hydrophilic",
        "G": "neutral",
        "H": "neutral",
        "I": "hydrophobic",
        "L": "hydrophobic",
        "K": "hydrophilic",
        "M": "hydrophobic",
        "F": "hydrophobic",
        "P": "neutral",
        "S": "neutral",
        "T": "neutral",
        "W": "hydrophobic",
        "Y": "neutral",
        "V": "hydrophobic",
    },
    'volume_classes': {
        "A": "very small",
        "R": "large",
        "N": "small",
        "D": "small",
        "C": "small",
        "Q": "medium",
        "E": "medium",
        "G": "very small",
        "H": "medium",
        "I": "large",
        "L": "large",
        "K": "large",
        "M": "large",
        "F": "very large",
        "P": "small",
        "S": "very small",
        "T": "small",
        "W": "very large",
        "Y": "very large",
        "V": "medium",
    },
    'chemical_classes': {
        "A": "aliphatic",
        "R": "basic",
        "N": "amide",
        "D": "acidic",
        "C": "sulfur",
        "Q": "amide",
        "E": "acidic",
        "G": "aliphatic",
        "H": "basic",
        "I": "aliphatic",
        "L": "aliphatic",
        "K": "basic",
        "M": "sulfur",
        "F": "aromatic",
        "P": "aliphatic",
        "S": "hydroxyl",
        "T": "hydroxyl",
        "W": "aromatic",
        "Y": "aromatic",
        "V": "aliphatic",
    },
    'physicochemical_classes': {
        "A": "aliphatic",
        "R": "basic",
        "N": "amide",
        "D": "acidic",
        "C": "sulfur",
        "Q": "amide",
        "E": "acidic",
        "G": "G",
        "H": "basic",
        "I": "aliphatic",
        "L": "aliphatic",
        "K": "basic",
        "M": "sulfur",
        "F": "F",
        "P": "P",
        "S": "hydroxyl",
        "T": "hydroxyl",
        "W": "W",
        "Y": "Y",
        "V": "aliphatic",
    },
    'charge_classes': {
        "A": "uncharged",
        "R": "positive charged",
        "N": "uncharged",
        "D": "negative charged",
        "C": "uncharged",
        "Q": "uncharged",
        "E": "negative charged",
        "G": "uncharged",
        "H": "positive charged",
        "I": "uncharged",
        "L": "uncharged",
        "K": "positive charged",
        "M": "uncharged",
        "F": "uncharged",
        "P": "uncharged",
        "S": "uncharged",
        "T": "uncharged",
        "W": "uncharged",
        "Y": "uncharged",
        "V": "uncharged",
    },
    'polarity_classes': {
        "A": "nonpolar",
        "R": "polar",
        "N": "polar",
        "D": "polar",
        "C": "nonpolar",
        "Q": "polar",
        "E": "polar",
        "G": "nonpolar",
        "H": "polar",
        "I": "nonpolar",
        "L": "nonpolar",
        "K": "polar",
        "M": "nonpolar",
        "F": "nonpolar",
        "P": "nonpolar",
        "S": "polar",
        "T": "polar",
        "W": "nonpolar",
        "Y": "polar",
        "V": "nonpolar",
    },
    'hydrogen_donor_acceptor_classes': {
        "A": "none",
        "R": "donor",
        "N": "donor and acceptor",
        "D": "acceptor",
        "C": "none",
        "Q": "donor and acceptor",
        "E": "acceptor",
        "G": "none",
        "H": "donor and acceptor",
        "I": "none",
        "L": "none",
        "K": "donor",
        "M": "none",
        "F": "none",
        "P": "none",
        "S": "donor and acceptor",
        "T": "donor and acceptor",
        "W": "donor",
        "Y": "donor and acceptor",
        "V": "none",
    }
}
